# -*- coding: utf-8 -*-
"""신입생세미나과제.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MFLYeCVkI-B0dPqV-e_DznAik0wNj9LD
"""

#알고리즘 함수

def water(height):
  sum = 0 # 초기 반환값은 0으로 설정한다
  for i in range(1, max(height)+1): # y축기준으로 1부터 하나씩 올라가며, 해당 y영역에서 가둘 수 있는 물의 양을 탐색한다
      temp = [] # 고정된 y값에 담이 있는 x 값을 저장하는 리스트
      for j in range(len(height)): # x좌표를 탐색하면서
        if height[j] >= i: # 담으로 막혀있는 좌표를 temp에 추가한다.
          temp.append(j)
      if len(temp) <= 1: return sum; # 동일 높이에 담이 1개 이하라면 그y 와 그보다 더 높은 y에서는 물을 가둘 수 없다.
      for k in range(1, len(temp)): # 두개의 담 사이에 있는 영역의 길이를 재서, sum에 추가한다.
        sum += ((temp[k] - temp[k-1])-1)
  return sum

ex1 = [0,1,0,2,1,0,1,3,2,1,2,1]
print(water(ex1))
ex2 = [4,3,1,2,1,5]
print(water(ex2))
ex3 = [1,0,0,2,1,0,1,4]
print(water(ex3))

list(enumerate(height))[3][1]